### ISSUE TITLE
Option to specify the frequency of updates

### ISSUE THREAD

**Issue by azekeil** [radiantly/live-countdown-bot#16]
Perhaps as a series of tuples of <time left>: <update frequency>, e.g.:
```
!countdown 10mins 10mins: 1min, 1min: 10sec, 10sec: 1 sec 
```

**Comment by radiantly** [comment]
Hmm could you elaborate on how something like this would work?

The current behavior increases the frequency of updates as the countdown grows nearer.
if time left is lower than 2 days, then it is updated every minute.
else, if lower than 2 weeks, it is updated every hour.
else it is updated every day.

I'm also not very sure if this option should be given to the users - having a countdown that ends in a year or so update every minute seems like an awful waste of resources.

Updates every second is not possible with Discord's current API limits.

**Comment by azekeil** [comment]
I wasn't aware (I don't think it's documented) about the current behaviour. That seems sensible enough as it is, thanks. Closing this issue (although you might want to consider adding it to the documentation?)

**Comment by radiantly** [comment]
Fair enough, the current behavior needs to be documented.
