### ISSUE TITLE
An error when I node in the CMD 

### ISSUE THREAD

**Issue by mariocmg** [radiantly/live-countdown-bot#17]
The first time that I do node index.js appears this in the CMD
![image](https://user-images.githubusercontent.com/38396612/102595239-8ff23300-4117-11eb-9ac7-ae0ea273addf.png)
Anyone know how to solve?

**Comment by radiantly** [comment]
Please copy the contents of `config.example.js` to `config.js` with your bot token and relevant config.

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/102650662-8c889700-416b-11eb-9ac9-fcbb236226eb.png)
Now appears this

**Comment by radiantly** [comment]
`npm install`

**Comment by mariocmg** [comment]
Appears the same

**Comment by radiantly** [comment]
The error clearly states that you have not installed the `better-sqlite3` module.

**Comment by mariocmg** [comment]
npm i better-sqlite3 (I put the this in the CMD to install)
 I install the better-sqlite3 but appears the same

**Comment by mariocmg** [comment]
Do you know what happen?

**Comment by radiantly** [comment]
I'm not sure why it does not work on your side.

I run the bot on the latest commit of the `master` branch, and do not have any problems (check the output of `!botstats` to see the current NodeJS version and commit hash).

**Comment by mariocmg** [comment]
I'm going to install node again and the code to see if  now works

**Comment by mariocmg** [comment]
Now work perfect

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/102774418-38f49400-438b-11eb-8e9c-3153c7a1f1d6.png)
It is possible to change the minutes to minutos

**Comment by mariocmg** [comment]
I've been looking at the code but didn't find anything, where is it?

**Comment by radiantly** [comment]
To use spanish, use this command: `!countdown es 50mins`

**Comment by radiantly** [comment]
Languages can be found in https://github.com/radiantly/live-countdown-bot/blob/master/modules/lang.js

**Comment by mariocmg** [comment]
And in plural?

**Comment by radiantly** [comment]
By default, the plural is the singular with an `s`. If you'd like a different plural, add it as a key in `lang.js`

**Comment by mariocmg** [comment]
What I have to write?

**Comment by mariocmg** [comment]
Thanks

**Comment by mariocmg** [comment]
Also where do you have the bot uploaded so that it is 24/7?

**Comment by radiantly** [comment]
I use an instance on Google Cloud Platform.
