### ISSUE TITLE
Countdown has wrong value

### ISSUE THREAD

**Issue by Demon-MoonBat** [radiantly/live-countdown-bot#19]
I told the bot to countdown to January 1st, midnight. It says eight hours and some minutes remaining, even though it's only just after 10am on the 31st. There's over 13 hours remaining. The countdown has the wrong amount of time listed!

**Comment by radiantly** [comment]
The countdown timer uses the GMT time zone by default. Could you try using the command `!countdown 1 Jan 12AM :your_timezone_here:`?

**Comment by Demon-MoonBat** [comment]
Yes, that worked, thank you.
