### ISSUE TITLE
Add documentation about specific role tagging

### ISSUE THREAD

**Issue by ProditorMagnus** [radiantly/live-countdown-bot#21]
!countdown [tagme|taghere|tageveryone] is short way, but there is also !countdown tag \<rolename>

**Comment by radiantly** [comment]
There are multiple features that are actually undocumented, but have not been added to `!help` because it is already overwhelmingly long. Maybe we can add a `!help advanced` or equivalent for these features.

**Comment by ProditorMagnus** [comment]
I was looking for way to add extra information to "Countdown done!" message too, but from source code review it did not look possible.

**Comment by radiantly** [comment]
Hmm yes, it is not possible as of now. I plan to add this feature once slash commands are supported on Discord.js
