### ISSUE TITLE
Ping: Time Left / ETA

### ISSUE THREAD

**Issue by johnnyshankman** [radiantly/live-countdown-bot#30]
`!countdown eta` should respond with the amount of time left on the countdown that i have `tageveryone` set to.

If there is a way, the documentation doesn't show it.

Everyone wants to check in on the timer and cannot.

**Comment by TheRealHypo** [comment]
In a very active channel a long running timer gets lost very fast. 

So after a set amount of messages it might be wise to bump the countdown message down in chat. Some Warning/Alert Bots do that by removing their own message and sending a new one so it's always the latest one.

**Comment by PocketHero** [comment]
There are a lot of people that dislike how "spammy" those force bump bots are.

**Comment by johnnyshankman** [comment]
> There are a lot of people that dislike how "spammy" those force bump bots are.

make it a DM response then
