### ISSUE TITLE
Bot offline

### ISSUE THREAD

**Issue by simonSlamka** [radiantly/live-countdown-bot#40]
Hey,

I was interested in a countdown feature for my server, found your bot, invited it to the server, only to discover that it's offline.

Is there a timeline as to when approximately it will go back online if it ever will?

Thanks

**Comment by radiantly** [comment]
Hi there! We're having a bit of hosting issue which is why the bot isn't online currently. We've currently started a [Patreon](https://patreon.com/livecountdownbot) to help fund better servers for the bot.

**Comment by simonSlamka** [comment]
> Hi there! We're having a bit of hosting issue which is why the bot isn't online currently. We've currently started a [Patreon](https://patreon.com/livecountdownbot) to help fund better servers for the bot.

Copy that. Thanks
