### ISSUE TITLE
Custom message when countdown complete

### ISSUE THREAD

**Issue by PatrickRose** [radiantly/live-countdown-bot#9]
I have a use case where I'd like to set a timer for the different "phases" of a game I'm running. It would be really useful if I could do something like `!countdown tageveryone 10min Turn one Action phase`

**Comment by PatrickRose** [comment]
Though actually, having tested the bot a bit more, the inline commands kind of do this for me!

**Comment by radiantly** [comment]
@PatrickRose Will surely accept a PR, but there are two separate features that are being talked about.

1. Tag when the countdown is done (currently does not work for inline countdowns - this is why #6 is still open) -- This needs to be implemented first.
2. Custom message when the countdown is complete. At the moment, tageveryone simply sends a generic "Countdown done" message.

Also, readme installation instructions are outdated, now it's just an `npm i` and `npm start`.

**Comment by PatrickRose** [comment]
@radiantly I'll give it a go if I find the time!

**Comment by radiantly** [comment]
Tagging now works with inline countdowns, but it's the generic "Countdown down" message, so leaving this issue open till a custom message can be set.

**Comment by pokeponz** [comment]
Would also like to see custom Countdown Done messages. We have a use-case for this as well.

**Comment by radiantly** [comment]
The bot now has this feature! Pass in the `reason` argument to the `/countdown` slash command.
